// symbol name -> documentation URL.
var PLOTDEVICE_SYMBOL_DOCS = {
    // Canvas
    "size": "https://plotdevice.io/ref/Canvas#size()",
    "speed": "https://plotdevice.io/ref/Canvas#speed()",
    "background": "https://plotdevice.io/ref/Canvas#background()",
    "geometry": "https://plotdevice.io/ref/Canvas#geometry()",
    "export": "https://plotdevice.io/ref/Canvas#export()",
    "plot": "https://plotdevice.io/ref/Canvas#plot()",
    "clear": "https://plotdevice.io/ref/Canvas#clear()",
    "outputmode": "https://plotdevice.io/ref/Canvas#outputmode()",
    "ximport": "https://plotdevice.io/ref/Canvas#ximport()",
    "halt": "https://plotdevice.io/ref/Canvas#halt()",

    // Line & Color
    "color": "https://plotdevice.io/ref/Line+Color#color()",
    "stroke": "https://plotdevice.io/ref/Line+Color#stroke()",
    "fill": "https://plotdevice.io/ref/Line+Color#fill()",
    "pen": "https://plotdevice.io/ref/Line+Color#pen()",
    "capstyle": "https://plotdevice.io/ref/Line+Color#capstyle()",
    "colormode": "https://plotdevice.io/ref/Line+Color#colormode()",
    "joinstyle": "https://plotdevice.io/ref/Line+Color#joinstyle()",
    "nofill": "https://plotdevice.io/ref/Line+Color#nofill()",
    "nostroke": "https://plotdevice.io/ref/Line+Color#nostroke()",
    "strokewidth": "https://plotdevice.io/ref/Line+Color#strokewidth()",

    // Primitives
    "poly": "https://plotdevice.io/ref/Primitives#poly()",
    "rect": "https://plotdevice.io/ref/Primitives#rect()",
    "arc": "https://plotdevice.io/ref/Primitives#arc()",
    "oval": "https://plotdevice.io/ref/Primitives#oval()",
    "line": "https://plotdevice.io/ref/Primitives#line()",
    "image": "https://plotdevice.io/ref/Primitives#image()",
    "text": "https://plotdevice.io/ref/Primitives#text()",
    "arrow": "https://plotdevice.io/ref/Primitives#arrow()",
    "star": "https://plotdevice.io/ref/Primitives#star()",

    // Drawing
    "bezier": "https://plotdevice.io/ref/Drawing#bezier()",
    "moveto": "https://plotdevice.io/ref/Drawing#moveto()",
    "lineto": "https://plotdevice.io/ref/Drawing#lineto()",
    "arcto": "https://plotdevice.io/ref/Drawing#arcto()",
    "curveto": "https://plotdevice.io/ref/Drawing#curveto()",
    "autoclosepath": "https://plotdevice.io/ref/Drawing#autoclosepath()",
    "beginpath": "https://plotdevice.io/ref/Drawing#beginpath()",
    "drawpath": "https://plotdevice.io/ref/Drawing#drawpath()",
    "endpath": "https://plotdevice.io/ref/Drawing#endpath()",
    "findpath": "https://plotdevice.io/ref/Drawing#findpath()",

    // Transform
    "transform": "https://plotdevice.io/ref/Transform#transform()",
    "translate": "https://plotdevice.io/ref/Transform#translate()",
    "rotate": "https://plotdevice.io/ref/Transform#rotate()",
    "scale": "https://plotdevice.io/ref/Transform#scale()",
    "skew": "https://plotdevice.io/ref/Transform#skew()",
    "reset": "https://plotdevice.io/ref/Transform#reset()",
    "pop": "https://plotdevice.io/ref/Transform#pop()",
    "push": "https://plotdevice.io/ref/Transform#push()",

    // Compositing
    "alpha": "https://plotdevice.io/ref/Compositing#alpha()",
    "blend": "https://plotdevice.io/ref/Compositing#blend()",
    "shadow": "https://plotdevice.io/ref/Compositing#shadow()",
    "clip": "https://plotdevice.io/ref/Compositing#clip()",
    "mask": "https://plotdevice.io/ref/Compositing#mask()",
    "noshadow": "https://plotdevice.io/ref/Compositing#noshadow()",
    "beginclip": "https://plotdevice.io/ref/Compositing#beginclip()",
    "endclip": "https://plotdevice.io/ref/Compositing#endclip()",

    // Typography
    "font": "https://plotdevice.io/ref/Typography#font()",
    "layout": "https://plotdevice.io/ref/Typography#layout()",
    "stylesheet": "https://plotdevice.io/ref/Typography#stylesheet()",
    "paginate": "https://plotdevice.io/ref/Typography#paginate()",
    "textpath": "https://plotdevice.io/ref/Typography#textpath()",
    "align": "https://plotdevice.io/ref/Typography#align()",
    "fontsize": "https://plotdevice.io/ref/Typography#fontsize()",
    "lineheight": "https://plotdevice.io/ref/Typography#lineheight()",
    "textheight": "https://plotdevice.io/ref/Typography#textheight()",
    "textmetrics": "https://plotdevice.io/ref/Typography#textmetrics()",
    "textwidth": "https://plotdevice.io/ref/Typography#textwidth()",

    // Misc (Utility & Entropy)
    "read": "https://plotdevice.io/ref/Misc#read()",
    "measure": "https://plotdevice.io/ref/Misc#measure()",
    "files": "https://plotdevice.io/ref/Misc#files()",
    "fonts": "https://plotdevice.io/ref/Misc#fonts()",
    "var": "https://plotdevice.io/ref/Misc#var()",
    "imagesize": "https://plotdevice.io/ref/Misc#imagesize()",
    "open": "https://plotdevice.io/ref/Misc#open()",
    "random": "https://plotdevice.io/ref/Misc#random()",
    "choice": "https://plotdevice.io/ref/Misc#choice()",
    "shuffled": "https://plotdevice.io/ref/Misc#shuffled()",
    "ordered": "https://plotdevice.io/ref/Misc#ordered()",
    "grid": "https://plotdevice.io/ref/Misc#grid()",
    "autotext": "https://plotdevice.io/ref/Misc#autotext()",

    // Objects: Drawing
    "Bezier": "https://plotdevice.io/ref/Drawing#Bezier",
    "Curve": "https://plotdevice.io/ref/Drawing#Curve",
    "Image": "https://plotdevice.io/ref/Drawing#Image",
    "Context": "https://plotdevice.io/ref/Drawing#Context",

    // Objects: Line & Color
    "Color": "https://plotdevice.io/ref/Line+Color#Color",
    "Gradient": "https://plotdevice.io/ref/Line+Color#Gradient",
    "Shadow": "https://plotdevice.io/ref/Line+Color#Shadow",

    // Objects: Transform
    "Point": "https://plotdevice.io/ref/Transform#Point",
    "Size": "https://plotdevice.io/ref/Transform#Size",
    "Region": "https://plotdevice.io/ref/Transform#Region",
    "Transform": "https://plotdevice.io/ref/Transform#Transform",

    // Objects: Typography
    "Text": "https://plotdevice.io/ref/Typography#Text",
    "TextBlock": "https://plotdevice.io/ref/Typography#TextBlock",
    "TextFragment": "https://plotdevice.io/ref/Typography#TextFragment",
    "Font": "https://plotdevice.io/ref/Typography#Font",
    "Family": "https://plotdevice.io/ref/Typography#Family",

    // Constants
    "px": "https://plotdevice.io/ref/Misc#constants",
    "pica": "https://plotdevice.io/ref/Misc#constants",
    "inch": "https://plotdevice.io/ref/Misc#constants",
    "cm": "https://plotdevice.io/ref/Misc#constants",
    "mm": "https://plotdevice.io/ref/Misc#constants",
    "pi": "https://plotdevice.io/ref/Misc#constants",
    "tau": "https://plotdevice.io/ref/Misc#constants",
    "RGB": "https://plotdevice.io/ref/Misc#constants",
    "HSV": "https://plotdevice.io/ref/Misc#constants",
    "CMYK": "https://plotdevice.io/ref/Misc#constants",
    "CENTER": "https://plotdevice.io/ref/Misc#constants",
    "CORNER": "https://plotdevice.io/ref/Misc#constants",
    "DEGREES": "https://plotdevice.io/ref/Misc#constants",
    "RADIANS": "https://plotdevice.io/ref/Misc#constants",
    "PERCENT": "https://plotdevice.io/ref/Misc#constants",
    "LEFT": "https://plotdevice.io/ref/Misc#constants",
    "RIGHT": "https://plotdevice.io/ref/Misc#constants",
    "JUSTIFY": "https://plotdevice.io/ref/Misc#constants",
    "MOVETO": "https://plotdevice.io/ref/Misc#constants",
    "LINETO": "https://plotdevice.io/ref/Misc#constants",
    "CURVETO": "https://plotdevice.io/ref/Misc#constants",
    "CLOSE": "https://plotdevice.io/ref/Misc#constants",
    "MITER": "https://plotdevice.io/ref/Misc#constants",
    "ROUND": "https://plotdevice.io/ref/Misc#constants",
    "BEVEL": "https://plotdevice.io/ref/Misc#constants",
    "BUTT": "https://plotdevice.io/ref/Misc#constants",
    "SQUARE": "https://plotdevice.io/ref/Misc#constants",
    "NORMAL": "https://plotdevice.io/ref/Misc#constants",
    "FORTYFIVE": "https://plotdevice.io/ref/Misc#constants",
    "NUMBER": "https://plotdevice.io/ref/Misc#constants",
    "TEXT": "https://plotdevice.io/ref/Misc#constants",
    "BOOLEAN": "https://plotdevice.io/ref/Misc#constants",
    "BUTTON": "https://plotdevice.io/ref/Misc#constants",
    "WIDTH": "https://plotdevice.io/ref/Misc#constants",
    "HEIGHT": "https://plotdevice.io/ref/Misc#constants",
    "FRAME": "https://plotdevice.io/ref/Misc#constants",
    "PAGENUM": "https://plotdevice.io/ref/Misc#constants",
    "MOUSEX": "https://plotdevice.io/ref/Misc#constants",
    "MOUSEY": "https://plotdevice.io/ref/Misc#constants",
    "mousedown": "https://plotdevice.io/ref/Misc#constants",
    "KEY_UP": "https://plotdevice.io/ref/Misc#constants",
    "KEY_DOWN": "https://plotdevice.io/ref/Misc#constants",
    "KEY_LEFT": "https://plotdevice.io/ref/Misc#constants",
    "KEY_RIGHT": "https://plotdevice.io/ref/Misc#constants",
    "KEY_BACKSPACE": "https://plotdevice.io/ref/Misc#constants",
    "KEY_TAB": "https://plotdevice.io/ref/Misc#constants",
    "KEY_ESC": "https://plotdevice.io/ref/Misc#constants",

    // Dictionaries
    "adict": "https://plotdevice.io/ref/Misc#dictionaries",
    "ddict": "https://plotdevice.io/ref/Misc#dictionaries",
    "odict": "https://plotdevice.io/ref/Misc#dictionaries",
}
