#!/bin/sh

python=$(
    self=${0}
    while [ -L "${self}" ];
    do
        cd "${self%/*}"
        self=$(readlink "${self}")
    done
    cd "${self%/*}"
    echo "$(pwd -P)/python3"
)

if [ ! -x $python ]; then
    python=python3
fi

$python -m plotdevice $@