#!/bin/sh
export _p_l_o_t_d_e_v_i_c_e_=$(basename ${0})
python=$(
    self=${0}
    while [ -L "${self}" ];
    do
        cd "${self%/*}"
        self=$(readlink "${self}")
    done
    cd "${self%/*}"
    echo "$(pwd -P)/python3"
)

if [ ! -x $python ]; then
    python=python3
fi

$python -m plotdevice $@