name: Run tests
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      id: repo
      uses: actions/checkout@v3

    - name: Add missing setuptools
      run: brew install python-setuptools

    - name: Run tests
      run: python3 setup.py test
